### ISSUE TITLE
Netcode for GameObjects 1.0.0.pre-10: 'No suitable method found to override' error for OnIsServerAuthoritatitive() for ClientNetworkTransform

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.samples.coop#685]
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/9f183e9a8b955ce6d57593fb9b222a2632b79202/Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs#L43

I decided to update the version of Netcode for GameObjects on a project I'm working on from 1.0.0.pre-9 to 1.0.0.pre-10, and now this method is causing a compiler error:

`Library\PackageCache\com.unity.multiplayer.samples.coop@2bbc9f1cc2\Utilities\Net\ClientAuthority\ClientNetworkTransform.cs(43,33): error CS0115: 'ClientNetworkTransform.OnIsServerAuthoritatitive()': no suitable method found to override`

Looks like the rename of this method to `OnIsServerAuthoritative` in the base class is tbe the culprit, so this method will need to be renamed to fix that problem so it works on 1.0.0.pre-10.

**Comment by fernando-cortez** [comment]
Closing this issue as this breaking change has been accounted for inside of our latest release: https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/releases/tag/v1.3.0-pre.

**Comment by 11BelowStudio** [comment]
cool and also good thanks
