### ISSUE TITLE
Boss Room can't build with build Error

### ISSUE THREAD

**Issue by ohtaisao** [Unity-Technologies/com.unity.multiplayer.samples.coop#634]
**Describe the bug**
Boss Room can't build with build Error.

error CS0012: The type 'NativeHashMap<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Collections, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**To Reproduce**
* DownLoad project below
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/releases
* Build

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: [2021.3.1f1]
 - BossRoom Version: 1.1.2-pre

**Comment by SamuelBellomo** [comment]
If you clear your Library, do you still have this issue?
If you try with v1.2.0-pre do you still have this issue?

**Comment by SamuelBellomo** [comment]
If you try our develop branch, it has just been ported to 2021.3LTS do you see this issue?

**Comment by ohtaisao** [comment]
> If you clear your Library, do you still have this issue?
> If you try with v1.2.0-pre do you still have this issue?

I tried  Build with version v1.2.0-pre, And Build is Success.
